- name: variables 
  hosts: localhost
  vars: #variables (declaring var after hosts is called play level)
   course: "Ansible"
   Trainer: "Sivakumar"
   Duration: "120hrs"
  tasks: 
  - name: print info
    ansible.builtin.debug:
     msg: "hi, we are learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}." # we use {{}} for calling the vars
