- name: variables 
  hosts: localhost
  vars: #variables 
   course: "Ansible"
   Trainer: "sivakumar"
   Duration: "120hrs"
  tasks: 
  - name: print info
    ansible.builtin.debug:
     msg: "hi, we are learning {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}." # we use {{}} for calling the vars
