- name: variables
  hosts: localhost
  vars:
   course: "Terraform"
   trainer: "Siva"
   duration: "15hrs"
  tasks: 
  - name: print overridden info
    vars: #task level var
     course: "Devops" 
    ansible.builtin.debug:
     msg: "hi, we are learning {{course}} from trainer {{trainer}} duration is {{duration}}."
     
  - name: print info
    ansible.builtin.debug:
     msg: "hi, we are learning {{course}} from trainer {{trainer}} duration is {{duration}}."