- name: variablels from files
  hosts: localhost
  vars_files: #calling var
  - vars.yaml #file name
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "hi, i am learning {{Course}} from trainer {{Trainer}}, duration is {{Duration}}."