- name: variable preference
  hosts: localhost
  vars:
   WISHES: "morning from play"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: please enter WISHES
    private: false
  tasks:
  - name: check preference
  #  vars:
  #   WISHES: "morning from task"
    ansible.builtin.debug:
     msg: "hello, good {{WISHES}}"
       
  # 1st prefence is arguments
  # 2nd is task
  