- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{Friend | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
   greeting: "hello good morning" 
  tasks:
  - name: covert into upper case
    ansible.buitlin.debug:
     msg: "{{greeting | upper]}"    