- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "hello {{Friend | default('Ansible') }}"

- name: upper case
  hosts: localhost
  vars:
   greeting: "hello good morning" 
  tasks:
  - name: covert into upper case
    ansible.builtin.debug:
     msg: "{{greeting | upper}}"    

- name: lower case
  hosts: localhost
  vars:
   greeting: "HELLO GOOD MORNING"
  tasks:
  - name: convert into lower case
    ansible.builtin.debug:
     msg: "{{greeting | lower}}"  

- name: remove duplictes
  hosts: localhost
  vars:
   numbers: [1,2,2,5,3,7,7,99,55,54,87,77,3,77,107]         
  tasks:
  - name: remove duplicates 
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"

 - name: print min and max age
  hosts: localhost
  vars:
   ages: [1,2,2,5,3,7,7,99,55,54,87,77,3,77,107]         
  tasks:
  - name: print min and max age
    ansible.builtin.debug:   
     msg: "min age: {{ ages | min }}, max age: {{ ages | max }} " 