- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest' } #to install
    - { name: 'nginx', state: 'absent' } # to remove
    - { name: 'postfix', state: 'absent' } 